name: Patching version file
on:
  schedule:
    - cron: '0 17 * * * '
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run update script
        run: python3 compile.py
      - name: Commit changed versions
        run: |
          git config --global user.name 'cli-ish'
          git config --global user.email 'cli-ish@users.noreply.github.com'
          git add --all || true
          git commit -m "Automated update" || true
          git push || true