name: Push commit
on:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run update script
        run: python3 compile.py
      - name: Commit changed versions
        run: |
          git config --global user.name 'cli-ish'
          git config --global user.email 'cli-ish@users.noreply.github.com'
          git commit -all "Automated update"
          git push